### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by theKashey** [GoogleChromeLabs/buffer-backed-object#2]
Strict binary types ❤️ strict types

:ohplease:
> Would be glad to add it by myself if you don't have plans yet. It's more about adding it here or at `@types`

**Comment by RyanGuild** [comment]
`declare module "buffer-backed-object" {
  declare type DescriptorEntry<T = any> = T;
  declare type EndianOption = {
    endianess?: "big" | "little";
  };
  declare type BufferArrayOpts = {
    byteOffset?: number;
    length?: number;
  };
  declare type BufferDescriptor = {
    [key: string]: DescriptorEntry<any>;
  };

  declare function structSize(descriptor: BufferDescriptor): number;

  declare type BufferBackedObjectType = {
    new <T extends BufferDescriptor>(buffer: ArrayBuffer, descriptor: T): T;
    reserved(numBytes: number): DescriptorEntry<number>;
    Int8(): DescriptorEntry<number>;
    Uint8(): DescriptorEntry<number>;
    Int16(endianess?: EndianOption): DescriptorEntry<number>;
    Uint16(endianess?: EndianOption): DescriptorEntry<number>;
    Int32(endianess?: EndianOption): DescriptorEntry<number>;
    Uint32(endianess?: EndianOption): DescriptorEntry<number>;
    BigInt64(endianess?: EndianOption): DescriptorEntry<number>;
    BigUint64(endianess?: EndianOption): DescriptorEntry<number>;
    Float32(endianess?: EndianOption): DescriptorEntry<number>;
    Float64(endianess?: EndianOption): DescriptorEntry<number>;
    UTF8String(maxBytes: number): DescriptorEntry<string>;
    ArrayBuffer(size: number): DescriptorEntry<string>;
    NestedBufferBackedObject<E extends BufferDescriptor>(
      descriptors: E
    ): DescriptorEntry<E>;
    NestedArrayOfBufferBackedObjects<A extends BufferDescriptor>(
      numItems: number,
      descriptors: A
    ): DescriptorEntry<A[]>;
  };
  declare type ArrayOfBufferBackedObjectsType = {
    new <T extends BufferDescriptor>(
      buffer: ArrayBuffer,
      descriptors: T,
      options?: BufferArrayOpts
    ): T[];
  };

  declare const BufferBackedObject: BufferBackedObjectType;
  declare const ArrayOfBufferBackedObjects: ArrayOfBufferBackedObjectsType;
}`

**Comment by surma** [comment]
I added TypeScript support on v0.2.0 :)
