### ISSUE TITLE
Error: self is not defined

### ISSUE THREAD

**Issue by darky** [GoogleChromeLabs/buffer-backed-object#3]
Really, where `self` is defined?

https://github.com/GoogleChromeLabs/buffer-backed-object/blob/5bc79d95c0f149d077b053b1b0f320efe420d23d/buffer-backed-object.js#L130

Monkey-patch to `global` helps on node.js environment

**Comment by surma** [comment]
Hm, I should probably include `globalThis` polyfill. I wrote this for web, not Node

**Comment by surma** [comment]
I wrote this for web, not Node, so this is one of the places where things will go wrong :D

I should probably include `globalThis` polyfill.

**Comment by surma** [comment]
Fixed in v0.1.1

**Comment by darky** [comment]
Thanks!)
0.1.1 was published 17 days ago)
https://www.npmjs.com/package/buffer-backed-object/v/0.1.1

**Comment by surma** [comment]
Huh, `np` screwed me over then.

Published v0.1.2 :)
